[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
# [programs.devnet]
swap_program = "26SLSwPP1Ai5ECS38nd7Ju96KrBUB96mSB2KwziSCVSX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
# cluster = "devnet" 
wallet = "~/.config/solana/id.json"

[scripts]
# test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/tests/**/*.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

# upload-json = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/upload-json.test.ts"
# upload = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/upload.test.ts"
# token = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/util/token.ts"